### ISSUE TITLE
Change in cloud-init ssh keys list forces instance re-creation

### ISSUE THREAD

**Issue by konstantin-kornienko** [bpg/terraform-provider-proxmox#1239]
**Describe the bug**
If Cloud-init ssh keys list is changed in source code (block _initialization->user_account->keys_), terraform will re-create the instance

**To Reproduce**

1. Create the VM
```hcl

resource "proxmox_virtual_environment_vm" "proxmox_instance" {
 ...
  initialization {
    user_account {
      keys = [
        "ssh-ed25519 key1...."
      ]
    }
  }
}
```

2. Change the source code and apply
```hcl

resource "proxmox_virtual_environment_vm" "proxmox_instance" {
 ...
  initialization {
    user_account {
      keys = [
        "ssh-ed25519 key1...",
        "ssh-ed25519 key2...."
      ]
    }
  }
}
```

Terraform will try to recreate the instance

```
~ initialization {
  # proxmox_virtual_environment_vm.proxmox_instance must be replaced
-/+ resource "proxmox_virtual_environment_vm" "proxmox_instance" {
          ~ user_account {
              ~ keys     = [ # forces replacement
                    "ssh-ed25519 key1...",
                  + "ssh-ed25519 key2...",
                ]
            }
        }

```

**Expected behavior**
Cloud init SSH keys can be changed on an existing instance without re-creation. Terraform should update instance instead of recreating.

**Comment by bpg** [comment]
Hi @konstantin-kornienko! 👋🏼
This was discussed in #373, and the conclusion is that this is the expected behavior of the provider.
 
> Cloud init SSH keys can be changed on an existing instance without re-creation.

I assume you're talking about the changing them in the PVE UI? But would the key be applied to the VM? 
As far as I know, the cloud-init setup (at least in Proxmox, I'm not sure about a generic cloud init) is happening only at the first boot, so even if the key has changed, and the cloud-init image has regenerated, the VM won't pick it up at reboot, and needs to be re-created to apply the new key. A quick experiment in PVE UI confirmed that.

So the provider does not know the intention of the key change, and assumption has been made if the key (or anything else related to the user account) does change, the VM will be re-created to apply the changed value.

If you wish to ignore this behaviour, you can add
```hcl
lifecycle {
  ignore_changes = [
    initialization[0].user_account
  ]
}
```
to the template.

I'm open to discuss this further, but I'd need to know more about the use case you have in mind.

**Comment by konstantin-kornienko** [comment]
@bpg , thank you for the detailed explanation!

Yep, I see now that cc_ssh cloud-init module runs once, so updating ssh keys through Proxmox UI won't update them on instance after reboot.
In this case - yes, the tf module behavior is kind of correct.

I'd personally prefer to align the behavior with Proxmox UI/API, but of course, it's up to author!
