### ISSUE TITLE
disk file_format state is always qcow2

### ISSUE THREAD

**Issue by ednxzu** [bpg/terraform-provider-proxmox#129]
**Describe the bug**
When creating a new vm with `disk.file_format` as something other than "qcow2", the state of said disk will always be stored as qcow2, forcing re-create on re-apply.

**To Reproduce**
1. Create a VM with a disk that isn't qcow2 (raw or vmdk), `terrafrom apply` the configuration.
2. after it is created, `terraform apply` again
3. the plan should say that the vm you just created will be replaced.

**Expected behavior**
disk.file_format state should be stored according to the configuration file

Thanks for this provider ! It still misses some stuff, but it's already very good !

**Comment by bpg** [comment]
Yeah, I see the problem
<img width="541" alt="Screen Shot 2022-10-11 at 10 18 08 PM" src="https://user-images.githubusercontent.com/627562/195233754-05a4acca-421a-42de-b67f-42dd6715409c.png">

**Comment by bpg** [comment]
The problem is that the format is reported by API as an extension of the VM disk file, **not** as a key-value pair similar to other attributes. It is also omitted if the file format is default `qcow2`.

```
GET https://pve:8006/api2/json/nodes/pve/qemu/2041/config
```
```json
{
  "data": {
   -- skipped --

    "scsi1": "nfs:2041/vm-2041-disk-0.raw,discard=ignore,iothread=1,size=8G",
    "ide2": "local-lvm:vm-2041-cloudinit,media=cdrom,size=4M",
    "scsi0": "local-lvm:vm-2041-disk-0,discard=on,iothread=1,size=8G",

   -- skipped --
  }
}
```
But parser expects a `format` key-value 😞 https://github.com/bpg/terraform-provider-proxmox/blob/42e0e725a56db230f420ae5ad2f7616d838ae36c/proxmox/virtual_environment_vm_types.go#L1603

**Comment by bpg** [comment]
may also be related to #103
