### ISSUE TITLE
timeout while waiting for VM "7001" configuration to become unlocked

### ISSUE THREAD

**Issue by intelline** [bpg/terraform-provider-proxmox#133]
Problem: 
- I get **timeout while waiting for VM "7001" configuration to become unlocked** while cloning a template

Error: 
`proxmox_virtual_environment_vm.vm-test-debian: Still creating... [13m30s elapsed]
proxmox_virtual_environment_vm.vm-test-debian: Still creating... [13m40s elapsed]
proxmox_virtual_environment_vm.vm-test-debian: Still creating... [13m50s elapsed]
2022-10-12T10:01:44.827+0300 [ERROR] provider.terraform-provider-proxmox_v0.6.2: Response contains error diagnostic: tf_provider_addr=registry.terraform.io/example-namespace/example tf_resource_type=proxmox_virtual_environment_vm @caller=github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/diag/diagnostics.go:55 diagnostic_detail= diagnostic_severity=ERROR diagnostic_summary="timeout while waiting for VM "7001" configuration to become unlocked" tf_proto_version=5.3 tf_req_id=46a764bd-ee63-bfa4-d7d7-7f63685c30d4 tf_rpc=ApplyResourceChange @module=sdk.proto timestamp=2022-10-12T10:01:44.826+0300
2022-10-12T10:01:44.854+0300 [ERROR] vertex "proxmox_virtual_environment_vm.vm-test-debian" error: timeout while waiting for VM "7001" configuration to become unlocked
╷
│ Error: timeout while waiting for VM "7001" configuration to become unlocked
│
│   with proxmox_virtual_environment_vm.vm-test-debian,
│   on main.tf line 46, in resource "proxmox_virtual_environment_vm" "vm-test-debian":
│   46: resource "proxmox_virtual_environment_vm" "vm-test-debian" {
│`

How to replicate: 
`
terraform {
  required_providers {
    proxmox = {
      source  = "bpg/proxmox"
      version = "0.6.2"
    }
  }
}

provider "proxmox" {
  virtual_environment {
    endpoint = "https://XXXXXXX:8006"
    username = "xxxxx@pve"
    password = "xxxx"
    insecure = true
  }
}
resource "proxmox_virtual_environment_vm" "vm-test-debian" {
  name        = "terraform-vm1"
  description = "Managed by Terraform"

  node_name = "XX-node1"
  vm_id     = 7001

  clone {
    node_name = "XX-node1"
    vm_id     = 8000
    datastore_id = "slow"
  }
}`

**Comment by bpg** [comment]
I'm seeing similar timeouts time to time as well. I would say the provider is sensitive to increased IO delays on the PVE node, for example, if underlying storage is HDD rather than SDD. Quite annoying, but I wasn't able to pinpoint the issue so far.

**Comment by bpg** [comment]
@intelline, you may have an issue connecting with the qemu agent on the cloned VM. Please make sure the agent is enabled on the source vm (`8000`), and also check the status of the cloned VM (`7001`) in PVE after you've got an error from `terraform apply` -- it should show the agent as enabled, and you should also see the VM's IP address:
<img width="731" alt="Screen Shot 2022-10-16 at 11 29 38 PM" src="https://user-images.githubusercontent.com/627562/196083637-340788d2-396e-4182-9bd3-ad07d4c8a8eb.png">

<img width="566" alt="Screen Shot 2022-10-16 at 11 29 52 PM" src="https://user-images.githubusercontent.com/627562/196083650-72b69994-e210-43e4-a0f3-e8db626bd13c.png">

**Comment by xonvanetta** [comment]
I have the same timeout issue on some off my vm's, the common thing for those vm's are that they are k3s vm's with alot of networks. All are cloned from the same vm and those without k3s works like a charm. The only visible difference is that the network list contains also the CNI networks for k3s.

IO Should not be a problem here since i run this on a SSD and the overall io is pretty low

Maybe not the same issue?

**Comment by bpg** [comment]
> Maybe not the same issue?

Not sure... this particular error seems to be coming from https://github.com/bpg/terraform-provider-proxmox/blob/v0.6.2/proxmoxtf/resource_virtual_environment_vm.go#L1162
Which indicates that PVE didn't mark the VM as "ready" after 5min. Which support my previous suggestion that this could be related to some sort of resource constrains during the clone operation.

@intelline If the issue is reproducible, could you check in what state the cloned VM is in the PVE UI, right after you received the TF error?
