### ISSUE TITLE
Provider fails on Windows

### ISSUE THREAD

**Issue by codestrong** [bpg/terraform-provider-proxmox#255]
**Describe the bug**
I am using terraform on a Windows machine and it fails to connect to Proxmox with the following error:

```
proxmox_virtual_environment_file.user_config: Creating...
╷
│ Error: failed to read /.ssh/known_hosts: open /.ssh/known_hosts: The system cannot find the path specified.
│
│   with proxmox_virtual_environment_file.user_config,
│   on main.tf line 91, in resource "proxmox_virtual_environment_file" "user_config":
│   91: resource "proxmox_virtual_environment_file" "user_config" {
│
╵
```

The culprit appears to be this line:

https://github.com/bpg/terraform-provider-proxmox/blob/fcf98102522821c9dfb4534731747233bd627d38/proxmox/virtual_environment_nodes.go#L197

**Expected behavior**
The provider would recognize that it's running on Windows and act accordingly. Not sure what's the alternative to **known_hosts** file on Windows.

**Screenshots**
![image](https://user-images.githubusercontent.com/182750/224480952-6943d6d8-e8b6-42c3-8d74-aedb607a8428.png)

**Comment by bpg** [comment]
Hi @codestrong! 👋🏼
Thanks for the report! Have to admit, I'm not usually testing provider features on windows, so bugs like this can slip through the cracks.
I think the issue is that Windows has no `HOME` [environment variable](https://learn.microsoft.com/en-us/windows/deployment/usmt/usmt-recognized-environment-variables) set, it is using something like `%USERPROFILE%`.

Could you try running your plan with setting the variable, for example as `set HOME=%USERPROFILE% && terraform apply` to see if it helps?
