### ISSUE TITLE
Move api to separate repo

### ISSUE THREAD

**Issue by mikelsid** [bpg/terraform-provider-proxmox#423]
**Is your feature request related to a problem? Please describe.**
Hello, I wanted to consider moving the proxmox API to a separate repo
It has a much higher coverage than Telmate's and I think it could be easily added to the Proxmox wiki, hence attract more contributors
It's also currently impossible to import it to other projects, since the api uses custom types that are placed in internal package

**Comment by bpg** [comment]
I think this is a good idea, but i'm bit worried about extra complexity of managing changes across 2 repos. 

Started playing with it in 
- https://github.com/bpg/terraform-provider-proxmox/tree/move-api-client-out
- https://github.com/bpg/proxmox-api/tree/move-api-client

**Comment by FreekingDean** [comment]
Hey! I would love to help out here. I've been playing around with an autogenerated go api library for Proxmox. I run into some slight hiccups here & there (you can see from my last two commits) due to Proxmox's idea of a jsonschema not really being the best implementation of one, nor is the API. But it generally works pretty well.

I'd love more contribution if folks would like to help out.
https://pkg.go.dev/github.com/FreekingDean/proxmox-api-go
https://github.com/FreekingDean/proxmox-api-go

**Comment by FreekingDean** [comment]
Would be nice if folks using proxmox in go could use a single API that got all the love instead of everyone having to re-implement themselves via resty!

**Comment by bpg** [comment]
Hey @FreekingDean! 👋🏼

I'm contemplating your proposal for several days now, but can't commit myself to switching the underlying API client to a different one, it seems too much undertaking from my side, but with relatively low return value for the provider users.

If we have a bigger team of contributors here I would consider the switch, but for now my main long-term goal is to migrate from Terraform SDK to Terraform Plugin Framework, fixing long list of provider's state management issues along the road.

**Comment by bpg** [comment]
At this stage I don't think separating Proxmox API client from the provider will be beneficial. We keep changing the API layer, and separation only adds to the maintenance headache.
