### ISSUE TITLE
ability to start/stop VM

### ISSUE THREAD

**Issue by si458** [bpg/terraform-provider-proxmox#448]
**Is your feature request related to a problem? Please describe.**
currently i have to create 3 VMs first,
wait for the reply for the mac addresses of the vms,
then add the mac address as static ip entries in my vyos router (using another terraform provider)
but then i have to manually start the VMs via the web panel
**must be done in this order otherwise the vm starts too quickly and gets a random ip rather than the one ive set**

**Describe the solution you'd like**
the ability to start/stop the vm which is possible via the API 
https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/status/start
https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu/{vmid}/status/stop

**Describe alternatives you've considered**
add vms with `started=false` then add mac address static ips then start the vms manually

**Additional context**

**Comment by otopetrik** [comment]
>  but then i have to manually start the VMs via the web panel

There is no need to start VMs via the web panel.

Terraform files describe intended state, and running `terraform apply` attempts to modify actual resources to match intended state. Every VM is either intended to run (`started=true`) or not (`started=false`).
Changing the `started` value in .tf file and running `terraform apply` should start VMs which are inteded to be running, but are not (and stop VMs which .tf file intends to be not started, but which are currently running).

Creating VMs in `started=false` state *is* a valid way to have time to save MAC addresses to router configuration.

Especially for homelab use, where not all VMs run all the time, it may be actually the best one.
Instead of just editing 'started' in .tf file, it might be better to use a variable:

Something like:
`testcluster.tf:`
```
variable "testcluster_enabled" {
  type = bool
  default = false
}

resource "proxmox_virtual_environment_vm" "testcluster" {
  count = 5
  started = var.testcluster_enabled
  ...
}
```
`terraform apply` to create stopped VMs, and after configuring router 
`terraform.tfvars:`
```
testcluster_enabled=true
```
(this changes the value of variable 'tescluster_enabled' from false to true)
and
`terraform apply` to start the VMs (the intended state changed, `started` is now true, apply will modify the resources to match - i.e. start VMs).

This makes it easy to have multiple groups of VM, and just start/stop them as needed.  Especially if total memory requirements of all group together would exceed system RAM.

The downside is, that stopped VMs have empty IP address attributes, so other resource cannot really reference them.


For VM groups that get deleted and recreated, it may be better to have fixed MAC addresses - see '[network_device.mac_address](https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_vm#mac_address)' resource argument.

Simply pre-register a sequential group of locally administered MAC addresses in the router and make proxmox use them.
```
resource "proxmox_virtual_environment_vm" "testcluster" {
  count = 9
  network_device {
    bridge = "vmbr123"
    mac_address = "02:00:00:12:34:0${count.index}"
  }
  ...
}
```

**Comment by si458** [comment]
thanks for the suggestion @otopetrik!
this is actually linked to my other issue #449
because if i set the VM to start, it starts too quickly before vyos has replied it has added the static IP addresses, and the ip addresses are random not my static ones
so the ability to start/stop would be helpful

HOWEVER
i think i understand what you are saying,
`apply` with `started=false` to create vms and static ips etc
then edit `started=true` and `apply` again to start the vms
then maybe call `apply` a different TF file to actually create my talos cluster etc

i was hoping to try and do it all in 1 terraform file or at least seperate ones without running multiple commands
but i have a feeling thats not possible as if i disable the `agent` i have no way of say pinging the VM to check its alive before carrying on with the talos terraform commands

**Comment by bpg** [comment]
"Hey @si458 👋🏼 As @otopetrik mentioned, Terraform works with a declarative approach for defining resources. That means it's not the best fit for creating complex state transitions with conditions, branches, and so on.

So, for this feature request in general, I can't think of what else we could do on the provider level apart from the existing `started=true|false` attribute on the VM resource.

**Comment by si458** [comment]
@bpg you are correct as the idea is to automate the vm install via already configured stuff and not to configure stuff on the fly
