### ISSUE TITLE
Cloud-images should be downloaded directly on proxmox nodes instead of terraform controller

### ISSUE THREAD

**Issue by bitchecker** [bpg/terraform-provider-proxmox#638]
**Describe the bug**
When I try to create a template vm usign as source_path an URL to download a cloud-image, the file is previous downloaded on my local /tmp folder and after that is uploaded on proxmox node.

This is completely inefficient in time of space and time.

**To Reproduce**
1. Create a resource "proxmox_virtual_environment_file" configuring as `path` the url of the cloud-image
2. Run `terraform apply`
3. You'll see high incoming traffic on local machine and a file called `/tmp/downloadXXXX' after that an high outgoing traffic

**Expected behavior**
The download should be executed directly by the proxmox node

**Additional context**
- Single or clustered Proxmox: `single`
- Provider version (ideally it should be the latest version): `v0.35.0`
- Terraform version: `v1.6.2`
- OS (where you run Terraform from): `Fedora 38`

**Comment by bpg** [comment]
Hi @bitchecker!

I agree with you that this approach to file upload is inefficient, but the provider has to use this method due to limitations of the Proxmox API. You can find more details on this in the [proxmox_virtual_environment_file resource documentation](https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_file#important-notes).

A workaround for this would be to upload the file via the Proxmox UI and then reference it in your template, e.g.

```
  ...
  disk {
    datastore_id = "local-zfs"
    file_id      = "cephfs:iso/debian-12-genericcloud-amd64.img"
    interface    = "virtio0"
    iothread     = true
    discard      = "on"
    size         = 256
  }
  ...
```

To obtain the full file ID, you can use the following command in the PVE shell:

```
pvesm list <datastore id>
```

I hope this helps!

**Comment by DanielHabenicht** [comment]
@bpg I get it that the API does not support chunked transfer encoding. But via the UI I can still download files directly (as a job), is this something only added recently? 
![image](https://github.com/bpg/terraform-provider-proxmox/assets/13590797/7dd57344-3fdd-4c4d-9455-8fb1fe16d7c2)
![image](https://github.com/bpg/terraform-provider-proxmox/assets/13590797/6ad1a7c7-75b9-441c-b6de-1601c7a24d04)

Which calls the Endpoints: 
- Query: `GET https://192.168.178.147:8006/api2/extjs/nodes/pve/query-url-metadata?_dc=1699228087955&url=https%3A%2F%2Fcdimage.debian.org%2Fimages%2Fcloud%2Fbullseye%2F20221219-1234%2Fdebian-11-genericcloud-amd64-20221219-1234.qcow2&verify-certificates=1`
- Download: `POST https://192.168.178.147:8006/api2/extjs/nodes/pve/storage/local/download-url` with form-data: `content=iso&url=https%3A%2F%2Fcdimage.debian.org%2Fimages%2Fcloud%2Fbullseye%2F20221219-1234%2Fdebian-11-genericcloud-amd64-20221219-1234.qcow2&filename=debian-11-genericcloud-amd64-20221219-1234.iso&verify-certificates=1`

**Comment by ratiborusx** [comment]
Actually, yeah. Would be interested too if we could do something what @DanielHabenicht shows. It's not a complete a complete letdown but i've got a cluster with local storages only and i download all stuff on each node iteratively so this behavior creates some scalability problems.

**Comment by bpg** [comment]
Valid points, thanks @DanielHabenicht, @ratiborusx!
I'm converting this ticket to "enhancement".

**Comment by rafsaf** [comment]
I am also interested in this improvement and can try to help make it happen. I think it will be better to write new resource with new provider (Terraform Provider Framework) named like "proxmox_virtual_environment_download_file" with limited functionalities for a start probably (downloading iso like debian image for chosen nodes), but ideally only using proxmox API. I looked at the code of a current "proxmox_virtual_environment_file" and changes there or full rewriteto new provider is quite above my current GO lang capabilities -.- 

And since it is stable and works (not perfectly, but still), maybe there is no need to mess it up with changes like that.
