### ISSUE TITLE
Cloud-Images file type problems

### ISSUE THREAD

**Issue by bitchecker** [bpg/terraform-provider-proxmox#641]
**Describe the bug**
If I try to download a cloud-image (usually provided as QCOW2 format) the upload to the proxmox node (https://github.com/bpg/terraform-provider-proxmox/issues/638) fails with a `wrong file extension` error

**To Reproduce**
1. Create a resource "proxmox_virtual_environment_file" configuring as path the url of the cloud-image (eg. https://download.fedoraproject.org/pub/fedora/linux/releases/38/Cloud/x86_64/images/Fedora-Cloud-Base-38-1.6.x86_64.qcow2)
2. Run `terraform apply`
3. See error: `Error: error uploading file to datastore xxx: received an HTTP 400 response - Reason: Parameter verification failed. (filename: wrong file extension)` [datastore is configured to accept ALL proxmox files]
4. If you try to configure the resource paramether `content_type` as iso or vztmpl you got the same error (expected values are: backup, iso, snippets or vztmpl).

**Expected behavior**
be able to download normally using content-type: iso

**Comment by bpg** [comment]
Thanks for the feedback @bitchecker!

Proxmox enforces specific conventions on file extensions for different content types, allowing only `.img` and `.iso` for "ISO image" content type. To work around this restriction, you can utilize the [`file_name` attribute](https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_file#file_name) to override the source file name.

I will leave this ticket open to improve documentation.

**Comment by ratiborusx** [comment]
I may be wrong but i don't think its supposed to work at all like that and its not a provider's problem but how Proxmox itself works and its validation giving you a trouble. Somehow Proxmox dudes didn't think to create some sort of storage for cloud-init images - only for iso (raw) ones which supposed to be used for user-guided installation. I think this resource only provides the same functionality that available via GUI, and you can't upload qcow2 images in there (only img and iso are accepted).
Which begs a question whether example given in the repo really supposed to work? Because it does.
https://github.com/bpg/terraform-provider-proxmox/blob/main/example/resource_virtual_environment_file.tf#L77

I think Proxmox people didn't intend ISO datastore to keep sparse images but it happen to be that img ones can be not only raw but also qcow2 ones. So my guess is we're kinda hijacking the system here. In normal usage (via GUI) you would be able to mount images from ISO datastore on CD drive only anyway.

I saw example vm resource in the repo and i THINK that we could force upload sparse cloud-init qcow2 image to ISO datastore and use it later in vm/template creation in disk {} via 'file_id'. But only if such image is with img extension. I'd be grateful if @bpg could provide a bit of clarification here :)

**Comment by bitchecker** [comment]
> Proxmox enforces specific conventions on file extensions for different content types, allowing only `.img` and `.iso` for "ISO image" content type. To work around this restriction, you can utilize the [`file_name` attribute](https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_file#file_name) to override the source file name.

Hi @bpg,
thanks for your reply!

The workaround works properly BUT, when I try to build the template, I get a timeout error: `Error: failed to dial X.X.X.X:22: dial tcp X.X.X.X:22: connect: connection timed out`
really I don't have idea about which kind of connection is trying to perform because I'm trying to perform a simple download of the cloud-image and a template creation of a never started vm (just to don't touch cloud-init, at the moment)

**Comment by bpg** [comment]
>I saw example vm resource in the repo and i THINK that we could force upload sparse cloud-init qcow2 image to ISO datastore and use it later in vm/template creation in disk {} via 'file_id'. But only if such image is with img extension. I'd be grateful if @bpg could provide a bit of clarification here :)

Your response is clear, but here's a slightly improved version for clarity and readability:

Yes, that's precisely how the provider works around this limitation :) Ubuntu cloud images are easier to handle since they are published with a ".img" extension. For other Linux distros, you may need to rename the files before uploading them, or you can have the provider handle the renaming for you using the `file_name` attribute.

> when I try to build the template, I get a timeout error: Error: failed to dial X.X.X.X:22: dial tcp X.X.X.X:22: connect: connection timed out
> really I don't have idea about which kind of connection is trying to perform because I'm trying to perform a simple download of the cloud-image and a template creation of a never started vm (just to don't touch cloud-init, at the moment)

The provider uses SSH connection (port 22) to import VM disks, as a workaround for yet another limitation of the Proxmox API. You can find more details and examples on how to configure an SSH connection in https://registry.terraform.io/providers/bpg/proxmox/latest/docs#ssh-connection

**Comment by bpg** [comment]
See https://github.com/bpg/terraform-provider-proxmox/issues/651#issuecomment-1780280812 for examples on how to provision a VM from qcow2.

Closing in favour of #651
