### ISSUE TITLE
Download file from URL, but not if it already exists

### ISSUE THREAD

**Issue by defnotcat** [bpg/terraform-provider-proxmox#673]
**Is your feature request related to a problem? Please describe.**

Using the `proxmox_virtual_environment_file` resource on an HTTP URL with `overwrite = false` does prevent an unnecessary download if the file already exists, but also makes the provider complain about it, "ruining" an otherwise successful run... because the file you wanted to download was already downloaded?

I'm not sure whether this is due to code limitations or a design decision, but I have to admit I fail to see in what scenario you would want the provider to act like that 😅

**Describe the solution you'd like**

Turning `overwrite` into `ignore_existing` seems to make the most sense, unless this behavior is intended and you wish to keep it, in which case it could be a complementary option instead.

Either way, if `ignore_existing` is `true` and the file already exists, nothing is downloaded, and the processing of that resource stops without making a fuss.

**Comment by bpg** [comment]
Hey @defnotcat,

It seems like you're talking about a situation where a file exists in Proxmox but not in your local state cache. This often happens when you've created a new `proxmox_virtual_environment_file` resource but haven't done a `terraform apply` for it yet, or run apply from a different folder and Terraform can't find a matching state.

In Terraform, your config files describe the desired state, and when you use `terraform apply`, Terraform tries to make the actual resources (in PVE) match that desired state. So, if your state is empty, Terraform will create what's needed, which includes downloading and uploading the file to PVE. The `overwrite = false` setting act only as a safety net to prevent file replacement. That's why the provider throws an error in this case -- a user applying a plan with unintended consequences (overwriting an existing file), which should be corrected. 

As long as the file resource is in your Terraform state and hasn't changed, the Terraform plugin won't download it again.

If you want to use an existing file from the PVE datastore in your Terraform plans without redownloading it, you'll need to [import it](https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_file#import) into your local state. This way, Terraform knows it's there, and you can reference it in other resources. Using a data source for the file would be a better option, but the provider hasn't implemented it yet.

Hope this clears things up! Feel free to ask if you've got more questions.

**Comment by defnotcat** [comment]
Thanks a bunch for this detailed explanation, `terraform import` is indeed what I was looking for :)
