### ISSUE TITLE
proxmox_virtual_environment_vm error on already existing vm's

### ISSUE THREAD

**Issue by joek-office** [bpg/terraform-provider-proxmox#731]
**Describe the bug**
i have a terraform script that create virtual machines in proxmox from netbox data. The intention is to align the virtual machine to the data from netbox. The terraform script is executed once a day or manually.
The initial creation of the vm's is running very well. But if i run the script in a situation where a virtual machine is already present in proxmox, the provider crashes with a error like the following:
```
│ Error: error creating VM: received an HTTP 500 response - Reason: unable to create VM 201 - VM 201 already exists on node 'mgmthost1'
│ 
│   with proxmox_virtual_environment_vm.virtual-machine["DE-FRA1-JOEK1"],
│   on netbox-to-proxmox-sync.tf line 50, in resource "proxmox_virtual_environment_vm" "virtual-machine":
│   50: resource "proxmox_virtual_environment_vm" "virtual-machine" {
``` 

**To Reproduce**
run terraform apply more than once

following ressource configuration is used:
```
resource "proxmox_virtual_environment_vm" "virtual-machine" {
  for_each = {
    for index, vm in data.netbox_virtual_machines.base_vm.vms:
    vm.name => vm
  }

  name   = each.value.name
  vm_id        = each.value.vm_id+100
  node_name   = "${ each.value.device_name == "DE-FRA1-MGMTHOST1" ? "mgmthost1" : (each.value.device_name == "DE-FRA1-MGMTHOST2" ? "mgmthost2" : (each.value.device_name == "DE-FRA1-MGMTHOST3" ? "mgmthost3" : "mgmthost1"))}"
  description = each.value.comments
  memory {
    dedicated = each.value.memory_mb
  }
  
  cpu {
    sockets   = 1
    cores     = each.value.vcpus
  }
  bios        = "ovmf"
  scsi_hardware = "virtio-scsi-pci"
  # iso         = "local:iso/Rocky-8.6-x86_64-minimal.iso"
  
  efi_disk {
    datastore_id = "local-zfs"
    pre_enrolled_keys = false
    type      = "4m"
    file_format = "raw"
  }

  dynamic disk {
    for_each = jsondecode(each.value.config_context).disks
    content {
      interface = "${disk.value.type}${disk.key}"
      size      = disk.value.size
      datastore_id = "local-zfs"
      file_format = "raw"
    }
  }

  dynamic network_device {
    for_each = jsondecode(each.value.config_context).interfaces
    content {
      model   = network_device.value.model
      bridge  = network_device.value.bridge
      # tag     = network.value.tag
    }
  }
}
```
Please also provide a minimal Terraform configuration that reproduces the issue.

**Expected behavior**
that the provider see's the already existing vm and doesn't crash. In best case changes to the vm should be recognized and applied to the vm in proxmox.

**Comment by otopetrik** [comment]
> **Expected behavior** that the provider see's the already existing vm and doesn't crash. In best case changes to the vm should be recognized and applied to the vm in proxmox.

From terraform's point of view, during `terraform plan` or `terraform apply`, that VM does not exist.
It is not recorded in terraform's state file (it was not created by any prior terraform run or imported using terraform import command), and terraform provider's resource's `ReadContext` is not called.

At `terraform apply`, the provider attempts to create the VM and proxmox server returns a failure due to VMID collision.

This can be considered a terraform bug or limitation. Many resource types have identifiers which could be used for automatic import (e.g. S3 bucket name or proxmox VMID). The upstream issue is [here](https://github.com/hashicorp/terraform/issues/19017).

At the moment, *there does not seem to be any supported/recommended way for a provider to have this auto-import functionality*.
(`CustomizeDiff` should run for new resource, so there is a *very slim* chance, that there is some way to "repurpose" it, not sure if anyone explored that.)

Consider manually running [`terraform import`](https://registry.terraform.io/providers/bpg/proxmox/latest/docs/resources/virtual_environment_vm#import) command for every already existing VMs which is not yet tracked by terraform.

Using [import blocks](https://developer.hashicorp.com/terraform/language/import#syntax) likely is not suitable for this case, it requires resources for *all* import blocks to already exist. An import block which cannot be imported (e.g. VM with given VMID does not yet exist) causes whole `terraform plan` to fail.

Another option might be to write a terraform module which would wrap a single VM. The module would create both `proxmox_virtual_environment_vm` resource and `netbox_virtual_machine` resource, and reuse that module for each VM. Possibly using something like [runatlantis](https://github.com/runatlantis/atlantis) to run `terraform apply`.

> **To Reproduce**
> run terraform apply more than once

Repeatedly running `terraform apply` should work without terraform attempting to recreate VMs created in previous run.
Make sure to keep `terraform.tfstate` file between `terraform apply` runs. Or configure a terraform backend like [HTTP](https://developer.hashicorp.com/terraform/language/settings/backends/http) or [S3](https://developer.hashicorp.com/terraform/language/settings/backends/s3).

**Comment by joek-office** [comment]
@otopetrik
Thanks for your explanations. have tried to build it up in this way and it works. Have tested in a Gitlab Pipeline and have to handle with artifacts from previous pipelines and so on. But, now it works.

Just another question, i have tested before the telmate/proxmox provider and with that provider the described functionality was given without any state file handling. Can you direct me in the direction what the other provider does in an other way?

Thanks and have a nice day.

**Comment by otopetrik** [comment]
> Just another question, i have tested before the telmate/proxmox provider and with that provider the described functionality was given without any state file handling.Can you direct me in the direction what the other provider does in an other way?

To effectively and *reliably* use terraform, terraform state between runs has to be preserved (either in `terraform.tfstate` or in some HTTP API, S3, etc...). There are resource types which do not even connect to any API server, they just rely on saving data in terraform state, e.g. [`random_password`](https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/password). Whithout access to state, each terraform run would re-generate new passwords.


Looking at source of telmate provider, its behavior is *scary*.
When creating VM, it looks for VM with [same `name`](https://github.com/Telmate/terraform-provider-proxmox/blob/master/proxmox/resource_vm_qemu.go#L994) (not even VMID, name!).

If it finds such existing VM, and if the VM resource being created is configured with [`force_create = false`](https://github.com/Telmate/terraform-provider-proxmox/blob/4c0c8fc37ed3f6316ad9392a46a0cf28c4654a11/proxmox/resource_vm_qemu.go#L1000), then it just modifies that [existing VM to match](https://github.com/Telmate/terraform-provider-proxmox/blob/4c0c8fc37ed3f6316ad9392a46a0cf28c4654a11/proxmox/resource_vm_qemu.go#L1129) the VM resource it was supposed to create ("recycling it").

E.g. if there is a powered off forgotten VM named `test01`, and new terraform project wants to create a VM named `test01`, instead of getting a new VM, the new project gets the forgotten old VM, probably including its disk contents.

Naming is also unfortunate, `force_create = true` is the safer option and `force_create = false` is the dangerous and default one!
The terrifying part is, that **`terraform plan` would show only that it would create a new VM, not that it would replace/modify an existing VM which happens to have the same name**.

Hypothetical case:
User makes a copy of a directory for a "production terraform project" (assuming auto allocated VMIDs) to perform some sort of "experiment". Does not change VM names in the copy.
Runs `terraform plan` in the "experiment" directory which shows that it will **only create new resources**, running `terraform apply` then **results in the takeover/modification** of original "production terraform project" VMs by resources described by "experiment". Likely causing outage, maybe data loss, and certainly chaos.
*The displayed plan does not match performed operations!*

(I have not tested this, it is just my understanding of telmate provider behavior from reading few lines of their CreateContext function. I may have missed something and be completely wrong.)

**Comment by joek-office** [comment]
Thank you very much for this, excessive and detailed, explanation.
The explanation helps me not only in this particular problem, also very much to understand what going on under the hood.

With the hypothetical case you described, it shows to me the better way that this provider is going.
