### ISSUE TITLE
Create api tokens through provider

### ISSUE THREAD

**Issue by camaeel** [bpg/terraform-provider-proxmox#740]
**Is your feature request related to a problem? Please describe.**
It would be usefull to create API tokens with this terraform provider

**Describe the solution you'd like**
Resource like: `virtual_environment_api_token` that would allow creation of proxmox API tokens. 

**Describe alternatives you've considered**
An alternative is to try use curl with null_resource to create this token. 

**Additional context**
N/A

**Comment by zimmertr** [comment]
This is a great idea. I currently use [Ansible](https://github.com/zimmertr/Bootstrap-Proxmox/tree/main/roles/create_user) to do so and would love to replace that role.

**Comment by camaeel** [comment]
@zimmertr I solved it using Mastercard's restapi provider:

```
resource "restapi_object" "cloud-controller-api-token" {
  object_id = var.cloud-controller-tokenid
  path = "/api2/json/access/users/${proxmox_virtual_environment_user.cloud-controller.user_id }/token/${var.cloud-controller-tokenid}"

  read_path = "/api2/json/access/users/${proxmox_virtual_environment_user.cloud-controller.user_id}/token/${var.cloud-controller-tokenid}"
  create_path = "/api2/json/access/users/${proxmox_virtual_environment_user.cloud-controller.user_id}/token/${var.cloud-controller-tokenid}"
  destroy_path = "/api2/json/access/users/${proxmox_virtual_environment_user.cloud-controller.user_id}/token/${var.cloud-controller-tokenid}"
  update_path = "/api2/json/access/users/${proxmox_virtual_environment_user.cloud-controller.user_id}/token/${var.cloud-controller-tokenid}"  

  force_new = [
    proxmox_virtual_environment_user.cloud-controller.user_id ,
    var.cloud-controller-tokenid,
  ]
  data = jsonencode(
    {
      privsep = false
    }
  )
}
```

and provider config:
```
provider "restapi" {
  uri = var.proxmox_endpoint
  write_returns_object = true
  headers = {
    "Authorization" = "PVEAPIToken=${var.proxmox_api_token}",
  }
}
```

**Comment by TheBelgarion** [comment]
Im currently creating API user group,role, api token in a previous tf script all with remote-exec pveum, because i cant lazy load it from file and i dont want it to be put in a data resource, because i dont want secrets in tfstate files.

init.tf creating user and 
* create the token calling pveum on proxmox and store it to a file as json
* download the json to the local machine

in the next tf ,where i use bpg, i then load the token from file 
  api_token = format("%s=%s", jsondecode(file("${local.FILE_API_TOKEN}")).full-tokenid, jsondecode(file("${local.FILE_API_TOKEN}")).value)
