### ISSUE TITLE
proxmox_virtual_environment_container user_account password in plain-text

### ISSUE THREAD

**Issue by aleprovencio** [bpg/terraform-provider-proxmox#789]
**Describe the bug**

Hi,
I have noticed that the `password` set on `user_account` on `proxmox_virtual_environment_container` is stored in `plain-text` on the state file

**To Reproduce**

1. Create a resource `proxmox_virtual_environment_container` setting a `password`
2. Check the state file (i.e. using `terraform state pull`)
3. See that password is in plain-text

**Expected behavior**
This password should be masked just like `proxmox_virtual_environment_vm` does

**Additional context**

- Single or clustered Proxmox: single
- Provider version (ideally it should be the latest version): 0.40.0
- Terraform version: 1.6.5
- OS (where you run Terraform from): Linux

**Comment by bpg** [comment]
If one needs to protect sensitive values in the state, OpenTofu's [State Encryption](https://opentofu.org/docs/language/state/encryption/) feature is a good option.

**Comment by bpg** [comment]
Terrafrom also [has options](https://developer.hashicorp.com/terraform/language/state/sensitive-data) to manage sensitive data in the state.
Closing the issue as it is outside of the provider's scope. The mentioned behaviour of masking passwords in `proxmox_virtual_environment_vm` is due to specifics of PVE API, and is not a provider's feature.
