### ISSUE TITLE
Add support for "G", "M" etc. disk size unit spec

### ISSUE THREAD

**Issue by bpg** [bpg/terraform-provider-proxmox#86]
Currently the unit of `virtual_environment_vm.disk.size` parameter is "gigabytes". Add ability to specify different units using G/GB, M/MB notation.

```
│ Error: Incorrect attribute value type
│ 
│   on main.tf line 117, in resource "proxmox_virtual_environment_vm" "example_vm":
│  117:     size         = "300G"
│ 
│ Inappropriate value for attribute "size": a number is required.

```

**Comment by bpg** [comment]
Hmmmm... The parsing code already exists: https://github.com/bpg/terraform-provider-proxmox/blob/380f07c3e20d5e19d22afa9ce1d28cff6665cd42/proxmoxtf/utils.go#L461-L492

**Comment by bpg** [comment]
If anyone would like to contribute, this seems to be an easy one.

**Comment by zeddD1abl0** [comment]
@bpg I'm happy to pick this one up, but I have a question regarding this code; why is the size stored in gigabytes? I understand that most HDDs would be of gigabyte size, but this function fails when you try to clone a VM with an efi disk that is measured in kilobytes.

Specifically, I have a number of templates that have a 528K EFI disk associated with them, and the provider chokes while trying to decode this drive because "K" is not a supported size extension. I attempted to quickly submit a pull request for this, but the tests for this function appear to expect the size to be gigabytes:

https://github.com/bpg/terraform-provider-proxmox/blob/5ffb7d5acc7ae9bc5948e3dbd4ef6e962e859453/proxmox/utils_test.go#L11-L41

I tried to investigate how and why you'd go with that as a standard, and I can see you use qemu-img to grow the HDD to the requested size in this line:

https://github.com/bpg/terraform-provider-proxmox/blob/5ffb7d5acc7ae9bc5948e3dbd4ef6e962e859453/proxmoxtf/resource/vm.go#L2217

Is that it? Have I missed anything in the logic? This appears to prevent the creation of anything that's not at least 1 gigabyte in size. After following through the logic, it seems to round up to the nearest whole gigabyte if `M`, `G`, or `T`, is specified, and dies if the value is anything but this.

If the above is all correct, I'd propose to base off of bytes, as qemu-img uses bytes by default, and expanding to bytes is super simple. Then, it's simply a case of changing the line above to remove the "G", changing the util function to multiply out to bytes, and adding in the newly expected values ("MB", "GB", "TB", "KB", "B", etc).

You could plausibly go to Kilobytes as the base unit, extending your limit from 512 Petabytes per disk to 512 Exabytes per disk...

As an aside, I notice that there is no way to provide an EFI disk for a VM. If I get the chance, I'll probably include that in another pull request and get it added.

**Comment by bpg** [comment]
Hey @zeddD1abl0 👋🏼 Thanks for taking a stab on this!

In addition to reference you've mentioned, there are also a few special cases in PVE where a size is expected to be set as an integer without any units. So my guess that was a main driving factor behind unification of all disk size values as "gigabytes" in the [original provider](https://github.com/danitso/terraform-provider-proxmox).

For example, https://pve.proxmox.com/pve-docs/pve-admin-guide.html#qm_configuration, see "the special syntax STORAGE_ID:SIZE_IN_GiB to allocate a new volume" for params `--ide[n]`, `--sata[n]`, etc. 
In provider we're using this approach in https://github.com/bpg/terraform-provider-proxmox/blob/8a2a3f7abf87e1bf0fdc68bba87b0de6ded87c01/proxmoxtf/resource/vm.go#L2505 or in https://github.com/bpg/terraform-provider-proxmox/blob/8a2a3f7abf87e1bf0fdc68bba87b0de6ded87c01/proxmoxtf/resource/container.go#L1067

So I'm not entirely sure how to proceed with this story. It seems like using units less than 1G won't work in all use cases. I would probably do something similar to this:
- if no units specified, then assume the value is in gigabytes;
- if units are specified, then convert to gigabytes rounding up; 
- if the result value is less than 1G, then throw an error;

**Comment by zeddD1abl0** [comment]
Cool. I can work with that. How do you feel about using Regex to do the matching? The current check allows for `80TG`, which will break the process. I'd propose the following Regex-based solution to prevent erroneous sizes from being provided. This forces the value to be in the format of "<numbers><possibly a space><size designation>"

```golang
re := regexp.MustCompile(`(?i)^([\d\.]+)\s?(m|mb|mib|g|gb|gib|t|tb|tib)$`)
matches := re.FindStringSubmatch(*size)
if len(matches) > 0 {
fsize, err := strconv.ParseFloat(matches[1], 64)
if err != nil {
	return -1, fmt.Errorf("cannot parse disk size \"%s\"", *size)
}
switch strings.ToLower(matches[2]) {
case "m", "mb", "mib":
	return int(math.Ceil(fsize * 1024)) , nil
case "g", "gb", "gib":
	return int(math.Ceil(fsize)), nil
case "t", "tb", "tib":
	return int(math.Ceil(fsize / 1024)), nil
case "p", "pb", "pib":
	return int(math.Ceil(fsize / 1024 / 1024)), nil
}
}

return -1, fmt.Errorf("cannot parse disk size \"%s\"", *size)
```

If you'd prefer me to follow the current format, I can do that too. I just wanted to double-check before I got too far ahead of myself.

**Comment by bpg** [comment]
I'm fine with regex :), just make sure it is cached and not compiled on each func invocation.

Also I'm not sure if we should go into the rabbit hole of MB vs MiB etc, as they mean [different things](https://digilent.com/blog/mib-vs-mb-whats-the-difference/). Have everything represented in power on 2 seems reasonable to me.

**Comment by bpg-dev** [comment]
This ask lives on in #1511 (P1, in progress) — linking the two so the design discussion here (unit parsing, rounding up to GiB, minimum size) isn't lost.
